### ISSUE TITLE
Fjern Tumblr og codingpirates.dk/diku

### ISSUE THREAD

**Issue by dybber** [dybber/diku.codingpirates.dk#7]
Flyt evt. videoer/historier over

**Comment by dybber** [comment]
https://codingpirates.dk/diku/ og undersider er nu fjernet!

**Comment by dybber** [comment]
Vi har ikke disse på: http://diku.codingpirates.dk - de var på Tumblr'en
- https://youtu.be/qcWTpXh-rOw
- https://www.instagram.com/p/BBAJjnXsKCX/
- https://codingpirates.dk/coding-pirates-diku-sejler-videre-til-spaendende-nye-lokaler/
- https://scratch.mit.edu/projects/96245906/
- ![25385386235_7d4e073999_o](https://cloud.githubusercontent.com/assets/55204/13703331/91e20040-e795-11e5-8a61-5e5aac505973.jpg)

**Comment by dybber** [comment]
Jeg har sat password på Tumblr'en, så nu er den sort-of disabled ind til videre.

**Comment by dybber** [comment]
Jeg overvejer at indsætte tingene fra Tumblr, men back-date dem til den dato de blev lagt op oprindeligt.

**Comment by Rotendahl** [comment]
Det er en god ide, at back-date dem. 
I stedet for at låse tumblr'en skal vi måske bare lave et link til diku.codingpirates.dk?

**Comment by dybber** [comment]
Vi har aldrig annonceret Tumblr'en til nogen, så den skal bare væk igen.
